version: '3'
services:
  web:
    build:
      .
    ports:
      - "8090:3000"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: node bin/www
