version: '3'
services:
  web:
    build:
      .
    ports:
      - "8090:3000"
    environment:
      - NODE_ENV=production
    working_dir: /home/node/app
    volumes:
      - "./:/home/node/app"
    command: bash -c "npm install && node bin/www"
