version: '3'
services:
  web:
    image: node:latest
    ports:
      - "8090:3000"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "npm install && node bin/www"
    restart: always
